"""Shell completion scripts generated from the argparse tree.

The scripts are derived from ``build_parser()`` at print time, so a new
subcommand or option completes the moment it exists; there is no second list
to keep in sync. Bash output stays compatible with the Bash 3.2 that macOS
still ships (no associative arrays), and zsh reuses it through bashcompinit.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass, field

SHELLS = ("bash", "zsh", "fish")


@dataclass
class _Option:
    flags: list[str]
    help: str
    takes_value: bool
    choices: list[str]


@dataclass
class _Command:
    path: tuple[str, ...]
    help: str = ""
    options: list[_Option] = field(default_factory=list)
    arguments: list[str] = field(default_factory=list)  # positional choices
    children: dict[str, _Command] = field(default_factory=dict)


def _clean_help(text: str | None) -> str:
    if not text or text == argparse.SUPPRESS:
        return ""
    return " ".join(text.replace("%(default)s", "").replace("(default: )", "").split())


def _walk(parser: argparse.ArgumentParser, path: tuple[str, ...], help_text: str = "") -> _Command:
    node = _Command(path=path, help=help_text)
    for action in parser._actions:  # argparse has no public introspection API
        if isinstance(action, argparse._SubParsersAction):
            helps = {choice.dest: choice.help for choice in action._choices_actions}
            for name, child in action.choices.items():
                node.children[name] = _walk(child, (*path, name), _clean_help(helps.get(name)))
        elif not action.option_strings:
            node.arguments.extend(str(c) for c in action.choices or ())
        else:
            node.options.append(_Option(
                flags=list(action.option_strings),
                help=_clean_help(action.help),
                takes_value=action.nargs != 0,
                choices=[str(c) for c in action.choices] if action.choices else [],
            ))
    return node


def _flatten(node: _Command) -> list[_Command]:
    out = [node]
    for child in node.children.values():
        out.extend(_flatten(child))
    return out


def _bash(root: _Command) -> str:
    nodes = _flatten(root)
    words, choices = [], []
    for node in nodes:
        key = " ".join(node.path)
        flags = [flag for opt in node.options for flag in opt.flags]
        words.append(
            f'    "{key}") subs="{" ".join(node.children)}"; args="{" ".join(node.arguments)}"; opts="{" ".join(flags)}" ;;'
        )
        for opt in node.options:
            if opt.choices:
                for flag in opt.flags:
                    choices.append(f'    "{key}|{flag}") echo "{" ".join(opt.choices)}" ;;')
            elif opt.takes_value:
                for flag in opt.flags:
                    choices.append(f'    "{key}|{flag}") echo "__value__" ;;')
    return f"""# bash completion for whykit (generated by `whykit completion bash`)
__whykit_words() {{
  case "$1" in
{chr(10).join(words)}
    *) subs=""; args=""; opts="" ;;
  esac
}}

__whykit_choices() {{
  case "$1|$2" in
{chr(10).join(choices)}
  esac
}}

_whykit() {{
  local cur="${{COMP_WORDS[COMP_CWORD]}}" prev="" path="" w i subs args opts values skip=0
  [ "$COMP_CWORD" -gt 0 ] && prev="${{COMP_WORDS[COMP_CWORD-1]}}"
  for ((i = 1; i < COMP_CWORD; i++)); do
    w="${{COMP_WORDS[i]}}"
    if [ "$skip" = 1 ]; then skip=0; continue; fi
    case "$w" in
      -*)
        [ -n "$(__whykit_choices "$path" "$w")" ] && skip=1
        continue ;;
    esac
    __whykit_words "$path"
    case " $subs " in *" $w "*) path="${{path:+$path }}$w" ;; esac
  done
  COMPREPLY=()
  values="$(__whykit_choices "$path" "$prev")"
  if [ "$values" = "__value__" ]; then
    return 0
  elif [ -n "$values" ]; then
    COMPREPLY=($(compgen -W "$values" -- "$cur"))
    return 0
  fi
  __whykit_words "$path"
  case "$cur" in
    -*) COMPREPLY=($(compgen -W "$opts" -- "$cur")) ;;
    *) [ -n "$subs$args" ] && COMPREPLY=($(compgen -W "$subs $args" -- "$cur")) ;;
  esac
  return 0
}}

complete -o default -o bashdefault -F _whykit whykit
"""


def _zsh(root: _Command) -> str:
    return (
        "#compdef whykit\n"
        "# zsh completion for whykit (generated by `whykit completion zsh`)\n"
        "(( $+functions[compdef] )) || { autoload -U +X compinit && compinit -i; }\n"
        "autoload -U +X bashcompinit && bashcompinit\n"
        + _bash(root).split("\n", 1)[1]
    )


def _fish_quote(text: str) -> str:
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _fish(root: _Command) -> str:
    lines = ["# fish completion for whykit (generated by `whykit completion fish`)"]
    nodes = _flatten(root)
    # A nested command name can also be a top-level one (`new evidence` vs
    # `evidence`), so a depth-1 condition excludes the parents that own it.
    owners: dict[str, list[str]] = {}
    for node in nodes:
        if len(node.path) == 2:
            owners.setdefault(node.path[1], []).append(node.path[0])

    def condition(node: _Command) -> str:
        if not node.path:
            return "__fish_use_subcommand"
        parts = [f"__fish_seen_subcommand_from {name}" for name in node.path]
        if len(node.path) == 1 and node.path[0] in owners:
            parts.append("not __fish_seen_subcommand_from " + " ".join(owners[node.path[0]]))
        if node.children:
            parts.append("not __fish_seen_subcommand_from " + " ".join(node.children))
        return "; and ".join(parts)

    for node in nodes:
        cond = _fish_quote(condition(node))
        for name, child in node.children.items():
            parent = "__fish_use_subcommand" if not node.path else condition(node)
            lines.append(f"complete -c whykit -n {_fish_quote(parent)} -f -a {name} -d {_fish_quote(child.help)}")
        if node.arguments:
            lines.append(f"complete -c whykit -n {cond} -f -a {_fish_quote(' '.join(node.arguments))}")
        for opt in node.options:
            spec = []
            for flag in opt.flags:
                if flag.startswith("--"):
                    spec.append(f"-l {flag[2:]}")
                elif len(flag) == 2:
                    spec.append(f"-s {flag[1:]}")
            if opt.choices:
                spec.append(f"-xa {_fish_quote(' '.join(opt.choices))}")
            elif opt.takes_value:
                spec.append("-r -F")
            lines.append(f"complete -c whykit -n {cond} {' '.join(spec)} -d {_fish_quote(opt.help)}")
    return "\n".join(lines) + "\n"


def render_completion(parser: argparse.ArgumentParser, shell: str) -> str:
    root = _walk(parser, ())
    if shell == "bash":
        return _bash(root)
    if shell == "zsh":
        return _zsh(root)
    if shell == "fish":
        return _fish(root)
    raise ValueError(f"unsupported shell: {shell}")
